server:
  port: 8764
spring:
  application:
    name: micro-monitor
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: ${management.server.servlet.context-path}/health
        health-check-interval: 15s
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/