server:
  port: 8888
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          username:
          password:
          uri: https://github.com/Jane09/config-repos
          search-paths: microframework
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/